# nginx.conf

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Necesario para React Router:
    # si recarga una ruta como /login o /admin, Nginx devuelve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}